# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marin/dev/git/TicTacToRec

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marin/dev/git/TicTacToRec

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marin/dev/git/TicTacToRec/CMakeFiles /home/marin/dev/git/TicTacToRec//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marin/dev/git/TicTacToRec/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tictactorec

# Build rule for target.
tictactorec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tictactorec
.PHONY : tictactorec

# fast build rule for target.
tictactorec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/build
.PHONY : tictactorec/fast

src/TTT/GameModeManager.o: src/TTT/GameModeManager.cpp.o
.PHONY : src/TTT/GameModeManager.o

# target to build an object file
src/TTT/GameModeManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GameModeManager.cpp.o
.PHONY : src/TTT/GameModeManager.cpp.o

src/TTT/GameModeManager.i: src/TTT/GameModeManager.cpp.i
.PHONY : src/TTT/GameModeManager.i

# target to preprocess a source file
src/TTT/GameModeManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GameModeManager.cpp.i
.PHONY : src/TTT/GameModeManager.cpp.i

src/TTT/GameModeManager.s: src/TTT/GameModeManager.cpp.s
.PHONY : src/TTT/GameModeManager.s

# target to generate assembly for a file
src/TTT/GameModeManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GameModeManager.cpp.s
.PHONY : src/TTT/GameModeManager.cpp.s

src/TTT/GameState.o: src/TTT/GameState.cpp.o
.PHONY : src/TTT/GameState.o

# target to build an object file
src/TTT/GameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GameState.cpp.o
.PHONY : src/TTT/GameState.cpp.o

src/TTT/GameState.i: src/TTT/GameState.cpp.i
.PHONY : src/TTT/GameState.i

# target to preprocess a source file
src/TTT/GameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GameState.cpp.i
.PHONY : src/TTT/GameState.cpp.i

src/TTT/GameState.s: src/TTT/GameState.cpp.s
.PHONY : src/TTT/GameState.s

# target to generate assembly for a file
src/TTT/GameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GameState.cpp.s
.PHONY : src/TTT/GameState.cpp.s

src/TTT/GridLogic.o: src/TTT/GridLogic.cpp.o
.PHONY : src/TTT/GridLogic.o

# target to build an object file
src/TTT/GridLogic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GridLogic.cpp.o
.PHONY : src/TTT/GridLogic.cpp.o

src/TTT/GridLogic.i: src/TTT/GridLogic.cpp.i
.PHONY : src/TTT/GridLogic.i

# target to preprocess a source file
src/TTT/GridLogic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GridLogic.cpp.i
.PHONY : src/TTT/GridLogic.cpp.i

src/TTT/GridLogic.s: src/TTT/GridLogic.cpp.s
.PHONY : src/TTT/GridLogic.s

# target to generate assembly for a file
src/TTT/GridLogic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/GridLogic.cpp.s
.PHONY : src/TTT/GridLogic.cpp.s

src/TTT/MonteCarloBot.o: src/TTT/MonteCarloBot.cpp.o
.PHONY : src/TTT/MonteCarloBot.o

# target to build an object file
src/TTT/MonteCarloBot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/MonteCarloBot.cpp.o
.PHONY : src/TTT/MonteCarloBot.cpp.o

src/TTT/MonteCarloBot.i: src/TTT/MonteCarloBot.cpp.i
.PHONY : src/TTT/MonteCarloBot.i

# target to preprocess a source file
src/TTT/MonteCarloBot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/MonteCarloBot.cpp.i
.PHONY : src/TTT/MonteCarloBot.cpp.i

src/TTT/MonteCarloBot.s: src/TTT/MonteCarloBot.cpp.s
.PHONY : src/TTT/MonteCarloBot.s

# target to generate assembly for a file
src/TTT/MonteCarloBot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/TTT/MonteCarloBot.cpp.s
.PHONY : src/TTT/MonteCarloBot.cpp.s

src/external/imgui/backends/imgui_impl_glfw.o: src/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : src/external/imgui/backends/imgui_impl_glfw.o

# target to build an object file
src/external/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : src/external/imgui/backends/imgui_impl_glfw.cpp.o

src/external/imgui/backends/imgui_impl_glfw.i: src/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : src/external/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
src/external/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : src/external/imgui/backends/imgui_impl_glfw.cpp.i

src/external/imgui/backends/imgui_impl_glfw.s: src/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : src/external/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
src/external/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : src/external/imgui/backends/imgui_impl_glfw.cpp.s

src/external/imgui/backends/imgui_impl_opengl3.o: src/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : src/external/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
src/external/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : src/external/imgui/backends/imgui_impl_opengl3.cpp.o

src/external/imgui/backends/imgui_impl_opengl3.i: src/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : src/external/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
src/external/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : src/external/imgui/backends/imgui_impl_opengl3.cpp.i

src/external/imgui/backends/imgui_impl_opengl3.s: src/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : src/external/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
src/external/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : src/external/imgui/backends/imgui_impl_opengl3.cpp.s

src/external/imgui/imgui.o: src/external/imgui/imgui.cpp.o
.PHONY : src/external/imgui/imgui.o

# target to build an object file
src/external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui.cpp.o
.PHONY : src/external/imgui/imgui.cpp.o

src/external/imgui/imgui.i: src/external/imgui/imgui.cpp.i
.PHONY : src/external/imgui/imgui.i

# target to preprocess a source file
src/external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui.cpp.i
.PHONY : src/external/imgui/imgui.cpp.i

src/external/imgui/imgui.s: src/external/imgui/imgui.cpp.s
.PHONY : src/external/imgui/imgui.s

# target to generate assembly for a file
src/external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui.cpp.s
.PHONY : src/external/imgui/imgui.cpp.s

src/external/imgui/imgui_demo.o: src/external/imgui/imgui_demo.cpp.o
.PHONY : src/external/imgui/imgui_demo.o

# target to build an object file
src/external/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_demo.cpp.o
.PHONY : src/external/imgui/imgui_demo.cpp.o

src/external/imgui/imgui_demo.i: src/external/imgui/imgui_demo.cpp.i
.PHONY : src/external/imgui/imgui_demo.i

# target to preprocess a source file
src/external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_demo.cpp.i
.PHONY : src/external/imgui/imgui_demo.cpp.i

src/external/imgui/imgui_demo.s: src/external/imgui/imgui_demo.cpp.s
.PHONY : src/external/imgui/imgui_demo.s

# target to generate assembly for a file
src/external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_demo.cpp.s
.PHONY : src/external/imgui/imgui_demo.cpp.s

src/external/imgui/imgui_draw.o: src/external/imgui/imgui_draw.cpp.o
.PHONY : src/external/imgui/imgui_draw.o

# target to build an object file
src/external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_draw.cpp.o
.PHONY : src/external/imgui/imgui_draw.cpp.o

src/external/imgui/imgui_draw.i: src/external/imgui/imgui_draw.cpp.i
.PHONY : src/external/imgui/imgui_draw.i

# target to preprocess a source file
src/external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_draw.cpp.i
.PHONY : src/external/imgui/imgui_draw.cpp.i

src/external/imgui/imgui_draw.s: src/external/imgui/imgui_draw.cpp.s
.PHONY : src/external/imgui/imgui_draw.s

# target to generate assembly for a file
src/external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_draw.cpp.s
.PHONY : src/external/imgui/imgui_draw.cpp.s

src/external/imgui/imgui_tables.o: src/external/imgui/imgui_tables.cpp.o
.PHONY : src/external/imgui/imgui_tables.o

# target to build an object file
src/external/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_tables.cpp.o
.PHONY : src/external/imgui/imgui_tables.cpp.o

src/external/imgui/imgui_tables.i: src/external/imgui/imgui_tables.cpp.i
.PHONY : src/external/imgui/imgui_tables.i

# target to preprocess a source file
src/external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_tables.cpp.i
.PHONY : src/external/imgui/imgui_tables.cpp.i

src/external/imgui/imgui_tables.s: src/external/imgui/imgui_tables.cpp.s
.PHONY : src/external/imgui/imgui_tables.s

# target to generate assembly for a file
src/external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_tables.cpp.s
.PHONY : src/external/imgui/imgui_tables.cpp.s

src/external/imgui/imgui_widgets.o: src/external/imgui/imgui_widgets.cpp.o
.PHONY : src/external/imgui/imgui_widgets.o

# target to build an object file
src/external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_widgets.cpp.o
.PHONY : src/external/imgui/imgui_widgets.cpp.o

src/external/imgui/imgui_widgets.i: src/external/imgui/imgui_widgets.cpp.i
.PHONY : src/external/imgui/imgui_widgets.i

# target to preprocess a source file
src/external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_widgets.cpp.i
.PHONY : src/external/imgui/imgui_widgets.cpp.i

src/external/imgui/imgui_widgets.s: src/external/imgui/imgui_widgets.cpp.s
.PHONY : src/external/imgui/imgui_widgets.s

# target to generate assembly for a file
src/external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/external/imgui/imgui_widgets.cpp.s
.PHONY : src/external/imgui/imgui_widgets.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tictactorec.dir/build.make CMakeFiles/tictactorec.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tictactorec"
	@echo "... src/TTT/GameModeManager.o"
	@echo "... src/TTT/GameModeManager.i"
	@echo "... src/TTT/GameModeManager.s"
	@echo "... src/TTT/GameState.o"
	@echo "... src/TTT/GameState.i"
	@echo "... src/TTT/GameState.s"
	@echo "... src/TTT/GridLogic.o"
	@echo "... src/TTT/GridLogic.i"
	@echo "... src/TTT/GridLogic.s"
	@echo "... src/TTT/MonteCarloBot.o"
	@echo "... src/TTT/MonteCarloBot.i"
	@echo "... src/TTT/MonteCarloBot.s"
	@echo "... src/external/imgui/backends/imgui_impl_glfw.o"
	@echo "... src/external/imgui/backends/imgui_impl_glfw.i"
	@echo "... src/external/imgui/backends/imgui_impl_glfw.s"
	@echo "... src/external/imgui/backends/imgui_impl_opengl3.o"
	@echo "... src/external/imgui/backends/imgui_impl_opengl3.i"
	@echo "... src/external/imgui/backends/imgui_impl_opengl3.s"
	@echo "... src/external/imgui/imgui.o"
	@echo "... src/external/imgui/imgui.i"
	@echo "... src/external/imgui/imgui.s"
	@echo "... src/external/imgui/imgui_demo.o"
	@echo "... src/external/imgui/imgui_demo.i"
	@echo "... src/external/imgui/imgui_demo.s"
	@echo "... src/external/imgui/imgui_draw.o"
	@echo "... src/external/imgui/imgui_draw.i"
	@echo "... src/external/imgui/imgui_draw.s"
	@echo "... src/external/imgui/imgui_tables.o"
	@echo "... src/external/imgui/imgui_tables.i"
	@echo "... src/external/imgui/imgui_tables.s"
	@echo "... src/external/imgui/imgui_widgets.o"
	@echo "... src/external/imgui/imgui_widgets.i"
	@echo "... src/external/imgui/imgui_widgets.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

